language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: yz/kPB4naktst8WW2o7y9QEBagQzcPkl+9DA9tqejFC4gLsDil9EI9ssScJxAs9OchfuNjHHU/7gGEXf+E/kHmE0X9ipLxlsGNQ9uSw7Hoekv3+hnS3HOtiHOQ3ajM5HGTRsplu0/RsUcTc1X5NwLtIycJSrZJLRORAJYCwm9foK2eziK//kUbIONJx4p3D49r8e0qi/Rup9nkhLbpQIT6cs5CfghY6SoDQLKYMK4+F8m7YbGPae49ig1PQ51lb2JP6Ms/TH31ZOyy/AbvIRQgyNAY2guU8FKkz1ow3RyOlfMzKMMCZOqNY97ybJdidPvgw3uS/FTa7QUIFM8kRE95HB4YlUUDadHjeX0sq79qYRK2Fh1iVX5DsX2mQ9eq/j0Ew/P/3jevn4p/oCKFswNMNGOl+gaMkyhGG01aGk/k0okPcVClPbECxMW5W6cbWdinmV0qLc8d9bVS7I8pNfM57t7+n99ABnT2FKT3oq6H8N5fUDWOTPg39qKq4V2vH96rnTmuuhsDQLp3UCeHub45tkBFP3n81ymXrUq69KSdEfkfUX7o4TNCuzCtkQgkkUEV6/FJf31V4VVwJDoZ7DQQbu8PIk759YTiqtYX5c4g/vbq+6/mJ+SyDULiFWZGI/xJ7b14SoGvydENYBE2CaJoNESrBKAINGOOD4UCooYxY=
